POST https://localhost:8080/webhook HTTP/1.1
User-Agent: XsollaAgent
Accept: application/json
Authorization: Signature 8e90a7ce16c3015333a20278fe060d3d8ac74da1
Content-Type: application/json
Accept-Encoding: gzip

{"notification_type":"user_validation","settings":{"project_id":12345,"merchant_id":54321},"user":{"email":"email@example.com","id":"user_2","name":"John Smith"}}